run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

linters:
  disable-all: true

  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - wsl
    - stylecheck
    - cyclop
    - prealloc
    - dupl
    - goimports

#    # To-DO
#    - funlen

#     # JSON camel want got 'categoryUUID' want 'categoryUuid'
#    - tagliatelle
#     # long lines
#    - lll

#    - tagalign
#    - wrapcheck
#    - goimports
#    - gosec
#    - execinquery

linters-settings:
  cyclop:
    max-complexity: 14
    package-average: 6.0
    skip-tests: true


