version: '3.9'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC

volumes:
  mysqldata:
    driver: local
